<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "layoutinfo"
 *
 * Auto generated by Extension Builder 2018-11-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'layoutinfo',
    'description' => 'Show information about the active backend layout for the current page in page module',
    'category' => 'be',
    'author' => 'Andreas Kiefer',
    'author_email' => 'kiefer@kiefer.koeln',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
